baseURL = "https://raysca.dev/"
languageCode = "en-us"
title = "Raysca Dev"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

defaultTheme = "dark"
themeColor = "#252627"

[params]
    description = "Raysca Dev"
    contentTypeName = "exp"
    title = "Raymond Ottun"
    subtitle = "Full Stack Developer"
    homeTitle = "Raymond Ottun"
    homeSubtitle = "London based full stack developer"
    keywords = "javavscript, golang, kubernetes, docker, nodejs, react, vuejs, postgres"
    copyright = "Raycas Dev 2019"
    readOtherPosts = "Read other posts"
    
    [params.logo]
        logoText = "$ raysca"
        logoHomeLink = "/"
    
    [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/sayjava"

    [[params.social]]
        name = "github"
        url  = "https://github.com/sayjava"

    [[params.social]]
        name = "linkedin"
        url  = "https://www.linkedin.com/in/raysca"
    

    [[params.social]]
        name = "medium"
        url  = "https://medium.com/@sayjava"

[author]
  name = "Raymond Ottun"
  homepage = "https://raysca.dev"
  twitter = "https://twitter.com/sayjava"


[menu]
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/index.html"