name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: '0.58.3'
  
    - name: Build
      run: hugo --gc --minify 

    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: public
        path: public

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: public

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:prod
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
